analyzer:
  exclude:
    - "test/"
linter:
  rules:
    prefer_double_quotes: false
    unawaited_futures: false
    public_member_api_docs: false
    diagnostic_describe_all_properties: false

    always_put_control_body_on_new_line: true
    avoid_as: true
    avoid_catching_errors: true
    avoid_double_and_int_checks: true
    avoid_empty_else: true
    avoid_field_initializers_in_const_classes: true
    avoid_init_to_null: true
    avoid_print: true
    avoid_private_typedef_functions: true
    avoid_redundant_argument_values: true
    avoid_renaming_method_parameters: true
    avoid_return_types_on_setters: true
    avoid_returning_null: true
    avoid_returning_null_for_future: true
    avoid_returning_null_for_void: true
    avoid_setters_without_getters: true
    avoid_single_cascade_in_expression_statements: true
    avoid_web_libraries_in_flutter: true
    camel_case_extensions: true
    camel_case_types: true
    cancel_subscriptions: true
    close_sinks: true
    control_flow_in_finally: true
    curly_braces_in_flow_control_structures: true
    empty_catches: true
    empty_constructor_bodies: true
    empty_statements: true
    file_names: true
    implementation_imports: true
    invariant_booleans: true
    iterable_contains_unrelated_type: true
    library_names: true
    library_prefixes: true
    no_duplicate_case_values: true
    non_constant_identifier_names: true
    null_closures: true
    package_names: true
    package_prefixed_library_names: true
    prefer_collection_literals: true
    prefer_constructors_over_static_methods: true
    prefer_contains: true
    prefer_function_declarations_over_variables: true
    prefer_inlined_adds: true
    prefer_interpolation_to_compose_strings: true
    prefer_iterable_whereType: true
    prefer_relative_imports: true
    prefer_void_to_null: true
    test_types_in_equals: true
    throw_in_finally: true
    type_init_formals: true
    unnecessary_await_in_return: true
    unnecessary_brace_in_string_interps: true
    unnecessary_const: true
    unnecessary_lambdas: true
    unnecessary_new: true
    unnecessary_null_aware_assignments: true
    unnecessary_null_in_if_null_operators: true
    unnecessary_overrides: true
    unnecessary_parenthesis: true
    unnecessary_statements: true
    use_function_type_syntax_for_parameters: true
    use_setters_to_change_properties: true
    valid_regexps: true
    void_checks: true